# Generated by Django 5.1.3 on 2024-12-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Codigo')),
                ('description', models.CharField(max_length=20, verbose_name='Description')),
            ],
            options={
                'verbose_name_plural': 'Modelos',
            },
        ),
    ]
